CREATE TABLE IF NOT EXISTS tickets (
  id VARCHAR(64) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(320) NOT NULL,
  room VARCHAR(255) NOT NULL,
  types JSON NOT NULL,
  title VARCHAR(255) NOT NULL,
  comment TEXT NOT NULL,
  risk BOOLEAN NOT NULL DEFAULT FALSE,
  photo VARCHAR(512) NULL,
  status ENUM('NOUVEAU', 'EN_COURS', 'EN_ATTENTE', 'TERMINE') NOT NULL DEFAULT 'NOUVEAU',
  handler VARCHAR(255) NOT NULL DEFAULT '',
  admin_comment VARCHAR(2000) NOT NULL DEFAULT ''
);
